f = str(input("Digite uma frase: ")).strip().upper()
l = str(input("Qual letra voce quer saber sobre?: ")).upper()
print(f"A letra {l} apareceu {f.count(l)} vezes,")
print(f"A letra {l} apareceu a primeira vez na posição {f.find(l)+1}")
print(f"A letra {l} apareceu pela ultima vez na posição {f.rfind(l)}")